using System.Collections;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
namespace Brotherhood
{
 public sealed class MainMenuController:MonoBehaviour
 {
  RectTransform safe,modal;Image progress,penitent;Text status,modalTitle,modalBody;Sprite[] penitentFrames;float animationClock;Button beginButton;Font originalFont;System.Collections.Generic.List<GameObject> modalItems=new System.Collections.Generic.List<GameObject>();
  void Awake()
  {
   if(FindAnyObjectByType<Camera>()==null){var camera=new GameObject("Main menu camera",typeof(Camera)).GetComponent<Camera>();camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=Color.black;camera.orthographic=true;camera.transform.position=new Vector3(0,0,-10);}
   var module=FindAnyObjectByType<InputSystemUIInputModule>();if(module==null){var events=new GameObject("Menu input",typeof(EventSystem),typeof(InputSystemUIInputModule));module=events.GetComponent<InputSystemUIInputModule>();}if(module.actionsAsset==null)module.AssignDefaultActions();
  }
  void Start(){Application.runInBackground=true;Application.targetFrameRate=60;AudioListener.volume=PlayerPrefs.GetFloat("BrotherhoodVolume",1);Build();
#if UNITY_EDITOR
   // The editor verification harness attaches centrally after domain reload.
#endif
  }
#if UNITY_EDITOR
  IEnumerator EditorVerify(){yield return new WaitForSecondsRealtime(.5f);var lines=new System.Collections.Generic.List<string>();System.Action<bool,string> check=(ok,label)=>lines.Add((ok?"PASS ":"FAIL ")+label);check(FindAnyObjectByType<MainMenuController>()!=null,"Main menu controller starts");check(FindAnyObjectByType<EventSystem>()!=null,"Touch, keyboard and controller event system exists");check(Resources.Load<Texture2D>("Menu/MainMenuBackgroundFrame")!=null,"Cropped original 640x360 background loaded");check(penitentFrames!=null&&penitentFrames.Length==22&&penitentFrames[0]!=null&&penitentFrames[21]!=null,"Original 22-frame Penitent menu animation loaded");check(safe.GetComponentsInChildren<Button>(true).Length==7,"New Game, Continue, Options, Extras and modal controls created");check(modal!=null&&!modal.gameObject.activeSelf,"Options overlay starts closed");System.IO.Directory.CreateDirectory("Documentation/Previews");ScreenCapture.CaptureScreenshot("Documentation/Previews/main-menu-playtest.png");yield return null;bool failed=lines.Exists(v=>v.StartsWith("FAIL"));System.IO.File.WriteAllText("Documentation/menu-playtest-results.txt",string.Join("\n",lines)+"\nRESULT: "+(failed?"FAILED":"PASSED"));System.IO.File.Delete("Temp/brotherhood-menu-verify");UnityEditor.EditorApplication.isPlaying=false;}
#endif
  void Build(){if(FindAnyObjectByType<EventSystem>()==null){new GameObject("Menu input",typeof(EventSystem),typeof(InputSystemUIInputModule));}var canvas=new GameObject("Main menu canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));canvas.GetComponent<Canvas>().renderMode=RenderMode.ScreenSpaceOverlay;var scale=canvas.GetComponent<CanvasScaler>();scale.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scale.referenceResolution=new Vector2(1280,720);scale.matchWidthOrHeight=.5f;safe=new GameObject("Safe area",typeof(RectTransform)).GetComponent<RectTransform>();safe.SetParent(canvas.transform,false);ApplySafe();Panel(safe,Vector2.zero,Vector2.one,new Color(.015f,.012f,.012f));Artwork("Menu/MainMenuBackgroundFrame",Vector2.zero,Vector2.one,Color.white,false);penitent=Artwork("Menu/Penitent_00",Vector2.zero,new Vector2(.8125f,1),Color.white,false);penitentFrames=new Sprite[22];for(int i=0;i<penitentFrames.Length;i++)penitentFrames[i]=LoadSprite("Menu/Penitent_"+i.ToString("00"));Panel(safe,new Vector2(.50f,0),Vector2.one,new Color(.02f,.015f,.014f,.62f));TextLabel("BLASPHEMOUS",new Vector2(.74f,.81f),new Vector2(560,80),50);TextLabel("BROTHERHOOD OF THE SILENT SORROW",new Vector2(.74f,.71f),new Vector2(560,40),18);beginButton=MenuButton("NEW GAME",new Vector2(.74f,.53f),Begin,true);bool saved=System.IO.File.Exists(System.IO.Path.Combine(Application.persistentDataPath,"brotherhood-save.json"));MenuButton("CONTINUE",new Vector2(.74f,.43f),Continue,saved);MenuButton("OPTIONS",new Vector2(.74f,.33f),ShowOptions,true);MenuButton("EXTRAS",new Vector2(.74f,.23f),ShowExtras,true);status=TextLabel(saved?"A PILGRIMAGE AWAITS":"",new Vector2(.74f,.13f),new Vector2(520,32),15);var back=Panel(safe,new Vector2(.57f,.075f),new Vector2(.92f,.09f),new Color(.12f,.08f,.06f));progress=Panel(back.rectTransform,Vector2.zero,Vector2.one,new Color(.75f,.15f,.08f));progress.type=Image.Type.Filled;progress.fillMethod=Image.FillMethod.Horizontal;progress.fillAmount=0;back.gameObject.SetActive(false);BuildModal();EventSystem.current.SetSelectedGameObject(beginButton.gameObject);}
  void BuildModal(){modal=Panel(safe,new Vector2(.53f,.14f),new Vector2(.96f,.86f),new Color(.018f,.014f,.014f,.98f)).rectTransform;var outline=modal.gameObject.AddComponent<Outline>();outline.effectColor=new Color(.72f,.48f,.2f);outline.effectDistance=new Vector2(2,-2);modalTitle=TextOn(modal,"",new Vector2(.5f,.88f),new Vector2(500,55),30);modalBody=TextOn(modal,"",new Vector2(.5f,.59f),new Vector2(490,190),19);modalBody.alignment=TextAnchor.UpperCenter;ModalButton("SETTING 1",.37f,OptionOne);ModalButton("SETTING 2",.27f,OptionTwo);ModalButton("SETTING 3",.17f,OptionThree);ModalButton("BACK",.07f,HideModal);modal.gameObject.SetActive(false);}
  Button ModalButton(string value,float y,UnityEngine.Events.UnityAction action){var bg=Panel(modal,new Vector2(.2f,y-.04f),new Vector2(.8f,y+.04f),new Color(.12f,.08f,.06f,.95f));var b=bg.gameObject.AddComponent<Button>();b.onClick.AddListener(action);var t=TextOn(bg.rectTransform,value,new Vector2(.5f,.5f),new Vector2(360,45),18);t.transform.SetAsLastSibling();modalItems.Add(bg.gameObject);return b;}
  Text TextOn(RectTransform parent,string value,Vector2 anchor,Vector2 size,int fs){var o=new GameObject(value,typeof(RectTransform),typeof(Text));var r=o.GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=r.anchorMax=anchor;r.pivot=new Vector2(.5f,.5f);r.sizeDelta=size;var t=o.GetComponent<Text>();if(originalFont==null)originalFont=Resources.Load<Font>("Fonts/MajesticExtended_Pixel_Scroll");t.font=originalFont!=null?originalFont:Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.text=value;t.fontSize=fs;t.alignment=TextAnchor.MiddleCenter;t.color=new Color(.9f,.68f,.3f);t.raycastTarget=false;return t;}
  void ShowOptions(){modal.gameObject.SetActive(true);modalTitle.text="OPTIONS";RefreshOptions();SetModalLabel(0,"TOUCH SIZE");SetModalLabel(1,"JOYSTICK MODE");SetModalLabel(2,"HAPTIC FEEDBACK");}
  void ShowExtras(){modal.gameObject.SetActive(true);modalTitle.text="EXTRAS";modalBody.text="THE ART OF CVSTODIA\n\nRestored Brotherhood gallery and credits\nfrom the locally supplied game data.";SetModalLabel(0,"AUDIO  "+Mathf.RoundToInt(AudioListener.volume*100)+"%");SetModalLabel(1,"PURGE SAVE");SetModalLabel(2,"CREDITS");}
  void OptionOne(){if(modalTitle.text=="OPTIONS"){float v=PlayerPrefs.GetFloat("BrotherhoodTouchScale",1);v=v<.9f?1:v<1.1f?1.2f:.8f;PlayerPrefs.SetFloat("BrotherhoodTouchScale",v);PlayerPrefs.Save();RefreshOptions();}else if(modalTitle.text=="PURGE PILGRIMAGE")ShowExtras();else{AudioListener.volume=AudioListener.volume>.75f?.5f:AudioListener.volume>.25f?0:1;PlayerPrefs.SetFloat("BrotherhoodVolume",AudioListener.volume);PlayerPrefs.Save();SetModalLabel(0,"AUDIO  "+Mathf.RoundToInt(AudioListener.volume*100)+"%");}}
  void OptionTwo(){if(modalTitle.text=="OPTIONS"){int fixedMode=1-PlayerPrefs.GetInt("BrotherhoodFixedJoystick",0);PlayerPrefs.SetInt("BrotherhoodFixedJoystick",fixedMode);PlayerPrefs.Save();RefreshOptions();}else if(modalTitle.text=="EXTRAS")ShowPurge();else if(modalTitle.text=="PURGE PILGRIMAGE")ShowExtras();}
  void OptionThree(){if(modalTitle.text=="OPTIONS"){PlayerPrefs.SetInt("BrotherhoodHaptics",1-PlayerPrefs.GetInt("BrotherhoodHaptics",1));PlayerPrefs.Save();RefreshOptions();}else if(modalTitle.text=="PURGE PILGRIMAGE")PurgeSave();}
  void ShowPurge(){modalTitle.text="PURGE PILGRIMAGE";modalBody.text="Erase the current pilgrimage, checkpoint and backup?\n\nThis action cannot be undone.";SetModalLabel(0,"KEEP SAVE");SetModalLabel(1,"CANCEL");SetModalLabel(2,"CONFIRM PURGE");}
  void PurgeSave(){string path=System.IO.Path.Combine(Application.persistentDataPath,"brotherhood-save.json");try{if(System.IO.File.Exists(path))System.IO.File.Delete(path);if(System.IO.File.Exists(path+".bak"))System.IO.File.Delete(path+".bak");PlayerPrefs.DeleteKey("BrotherhoodNewPilgrimage");PlayerPrefs.Save();status.text="PILGRIMAGE PURGED";HideModal();}catch(System.Exception e){modalBody.text="SAVE COULD NOT BE PURGED\n"+e.Message;}}
  void RefreshOptions(){float size=PlayerPrefs.GetFloat("BrotherhoodTouchScale",1);modalBody.text="TOUCH CONTROL SIZE  "+Mathf.RoundToInt(size*100)+"%\n\nJOYSTICK  "+(PlayerPrefs.GetInt("BrotherhoodFixedJoystick",0)==1?"FIXED":"FLOATING")+"\n\nHAPTICS  "+(PlayerPrefs.GetInt("BrotherhoodHaptics",1)==1?"ON":"OFF")+"\n\nSettings are saved for the next pilgrimage.";}
  void SetModalLabel(int index,string value){if(index<modalItems.Count)modalItems[index].GetComponentInChildren<Text>().text=value;}
  void HideModal(){modal.gameObject.SetActive(false);EventSystem.current.SetSelectedGameObject(beginButton.gameObject);}
  void Update(){if(penitentFrames==null||penitentFrames.Length==0)return;animationClock=(animationClock+Time.unscaledDeltaTime)%3.2f;int frame=Mathf.Min(penitentFrames.Length-1,Mathf.FloorToInt(animationClock/.145f));if(penitentFrames[frame]!=null)penitent.sprite=penitentFrames[frame];}
  void Begin(){PlayerPrefs.SetInt("BrotherhoodNewPilgrimage",1);PlayerPrefs.Save();StartCoroutine(Load());}void Continue(){PlayerPrefs.DeleteKey("BrotherhoodNewPilgrimage");StartCoroutine(Load());}
  IEnumerator Load(){status.text="LOADING PILGRIMAGE…";progress.transform.parent.gameObject.SetActive(true);var op=SceneManager.LoadSceneAsync("Brotherhood");op.allowSceneActivation=false;while(op.progress<.9f){progress.fillAmount=Mathf.Clamp01(op.progress/.9f);yield return null;}progress.fillAmount=1;yield return new WaitForSecondsRealtime(.15f);op.allowSceneActivation=true;}
  void ApplySafe(){var a=Screen.safeArea;float w=Mathf.Max(1,Screen.width),h=Mathf.Max(1,Screen.height);Vector2 min=a.position/new Vector2(w,h),max=(a.position+a.size)/new Vector2(w,h);safe.anchorMin=new Vector2(Mathf.Clamp01(min.x),Mathf.Clamp01(min.y));safe.anchorMax=new Vector2(Mathf.Clamp01(max.x),Mathf.Clamp01(max.y));safe.offsetMin=safe.offsetMax=Vector2.zero;}
  Image Panel(RectTransform parent,Vector2 min,Vector2 max,Color color){var o=new GameObject("Panel",typeof(RectTransform),typeof(Image));var r=o.GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=min;r.anchorMax=max;r.offsetMin=r.offsetMax=Vector2.zero;var i=o.GetComponent<Image>();i.color=color;return i;}
  Text TextLabel(string value,Vector2 anchor,Vector2 size,int fs){return TextOn(safe,value,anchor,size,fs);}
  Button MenuButton(string value,Vector2 anchor,UnityEngine.Events.UnityAction action,bool enabled){var i=Panel(safe,anchor-new Vector2(.17f,.041f),anchor+new Vector2(.17f,.041f),enabled?new Color(.12f,.08f,.06f,.95f):new Color(.05f,.045f,.045f,.85f));var b=i.gameObject.AddComponent<Button>();b.interactable=enabled;b.onClick.AddListener(action);var t=TextLabel(value,anchor,new Vector2(430,55),21);t.color=enabled?new Color(.9f,.68f,.3f):new Color(.35f,.32f,.3f);t.transform.SetAsLastSibling();return b;}
  Image Artwork(string resource,Vector2 min,Vector2 max,Color tint,bool preserve){var i=Panel(safe,min,max,tint);i.sprite=LoadSprite(resource);i.preserveAspect=preserve;i.raycastTarget=false;return i;}
  Sprite LoadSprite(string resource){var tex=Resources.Load<Texture2D>(resource);return tex==null?null:Sprite.Create(tex,new Rect(0,0,tex.width,tex.height),new Vector2(.5f,.5f));}
 }
}
